config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"


  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end


  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites,only:[:create, :destroy]
    resources :post_comments,only:[:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update]do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "daily_posts" => "users#daily_posts"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :chats, only: [:show, :create]
  
  resources :groups, only: [:new, :index, :show, :create, :edit, :update]do
    resource :group_users, only: [:create, :destroy]
    resources :event_notices, only: [:new, :create]
    get "event_notices" => "event_notices#sent"
  end

end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites_users, through: :favorites, source: :user

  has_many :view_counts, dependent: :destroy

  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps


  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) }
  scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) }
  scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) }
  scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) }


  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # 検索方法分岐
  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end

  end

  def save_tags(savebook_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - savebook_tags
    new_tags = savebook_tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    new_tags.each do |new_name|
      book_tag = Tag.find_or_create_by(name:new_name)
      self.tags << book_tag
    end
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
      unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
        current_user.view_counts.create(book_id: @book.id)
      end

    @book_new = Book.new
    @post_comment = PostComment.new
  end

  def index
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorites_users).sort{|a,b|
      b.favorites_users.includes(:favorites).where(created_at: from...to).size <=>
      a.favorites_users.includes(:favorites).where(created_at: from...to).size
    }
    @book = Book.new
    
    @books = Book.all.order(params[:sort])

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    tag_list = params[:book][:tag_name].split(',')
    if @book.save
      @book.save_tags(tag_list)
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  
  <div class="form-group">
    <%= f.label "Tag" %>
    <%= f.text_field :tag_name, class: 'form-control book_tag_name' %>
  </div>
  
    <% if book.id === nil %>
    <div class="form-group" id="star">
      <%= f.label :rate %>
      <%= f.hidden_field :rate, id: :review_star, class:'form-control' %>
    </div>
    
    <script>
    $(document).on('turbolinks:load', function() {
      $('#star').empty();
      $('#star').raty({
        size     : 36,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'book[rate]',
        half: true,
      });
    })
    </script>
  <% else %>
    <%= render "static_rate", book: book %>
  <% end %>
  
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr id="book_<%= book.id %>">
        <td><%= link_to user_path(book.user) do %>
          <%= image_tag book.user.get_profile_image("50x50") %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        
        <td>
          <% book.tags.each do |tag| %>
            <li style="list-style: none;">
            <%= link_to tag.name, search_path(content: tag.name, model:"tag", method: "perfect") %>
            </li>
          <% end %>
        </td>

        <td class="favorite-btn" >
          <%= render "favorites/favorite-btn", book: book %>
        </td>
        <td class="comments-count">
          コメント数：<%= book.post_comments.count %>
        </td>
        <td class="view-count">閲覧数: <%= book.view_counts.count %></td>
        <td><%= render "books/static_rate", book: book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_static_rate.html.erb
<div id="rate_<%= book.id %>" class="form-group"></div>
<script>
$(document).on('turbolinks:load', function() {
  $('#rate_<%= book.id %>').empty();
  $('#rate_<%= book.id %>').raty({
    size: 20,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= book.rate %>,
  });
});
</script>

app/views/books/edit.html.erb
<div class='container'>
  
    <%= render 'layouts/errors', obj: @book %>
 
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>

    <%= render 'layouts/errors', obj: @book %>

  <div class='row'>

    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to "新しい順", books_path(sort: 'created_at DESC') %> | <%= link_to "評価の高い順", books_path(sort: 'rate DESC') %>



      <%= render 'index', books: @books , book: @book  %>

    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>

      <%= render 'users/info', user: @book.user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr id="book_<%= @book.id %>">
          <td><%= link_to(@book.user) do%>
            <%= image_tag @book.user.get_profile_image("100x100") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td class="favorite-btn"><%= render "favorites/favorite-btn", book: @book %></td>
          <td class="comments-count">コメント数: <%= @book.post_comments.count %></td>
          <td class="view-count">閲覧数: <%= @book.view_counts.count %></td>
          <td><%= render "static_rate", book: @book %></td>

          <% if @book.user == current_user %>
            <td>
                <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %>
            </td>
            <td>
                <%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%>
            </td>
          <% end %>
        </tr>
        </table>

        <table class="post_comments">
          <%= render "post_comments/index", book: @book %>
        </table>

        <%= render "post_comments/form", book: @book, post_comment: @post_comment %>

    </div>
  </div>
</div>